"""Initial migration

Revision ID: ac11b87e3b20
Revises: 
Create Date: 2025-11-26 10:10:54.375054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac11b87e3b20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants_catalog',
    sa.Column('species_id', sa.String(), nullable=False),
    sa.Column('common_names', sa.JSON(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('water_frequency_days_min', sa.Integer(), nullable=True),
    sa.Column('water_frequency_days_max', sa.Integer(), nullable=True),
    sa.Column('soil_moisture_target_pct', sa.Integer(), nullable=False),
    sa.Column('soil_moisture_min_pct', sa.Integer(), nullable=False),
    sa.Column('drainage_required', sa.Boolean(), nullable=True),
    sa.Column('light_level', sa.String(), nullable=True),
    sa.Column('min_lux', sa.Integer(), nullable=True),
    sa.Column('optimal_lux_min', sa.Integer(), nullable=True),
    sa.Column('optimal_lux_max', sa.Integer(), nullable=True),
    sa.Column('temp_celsius_min', sa.Integer(), nullable=True),
    sa.Column('temp_celsius_optimal_min', sa.Integer(), nullable=True),
    sa.Column('temp_celsius_optimal_max', sa.Integer(), nullable=True),
    sa.Column('temp_celsius_max', sa.Integer(), nullable=True),
    sa.Column('humidity_pct_min', sa.Integer(), nullable=True),
    sa.Column('humidity_pct_optimal_min', sa.Integer(), nullable=True),
    sa.Column('humidity_pct_optimal_max', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.String(), nullable=True),
    sa.Column('toxicity_pets', sa.String(), nullable=True),
    sa.Column('toxicity_humans', sa.String(), nullable=True),
    sa.Column('health_indicators', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plant_scientific_name_search', 'plants_catalog', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_plants_catalog_id'), 'plants_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_plants_catalog_scientific_name'), 'plants_catalog', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_plants_catalog_species_id'), 'plants_catalog', ['species_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_plants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('pot_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'XLARGE', name='potsize'), nullable=True),
    sa.Column('pot_material', sa.Enum('TERRACOTTA', 'PLASTIC', 'CERAMIC_GLAZED', 'FABRIC', 'OTHER', name='potmaterial'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.Column('custom_moisture_target', sa.Integer(), nullable=True),
    sa.Column('custom_moisture_min', sa.Integer(), nullable=True),
    sa.Column('auto_watering_enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['plants_catalog.species_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plants_id'), 'user_plants', ['id'], unique=False)
    op.create_index(op.f('ix_user_plants_user_id'), 'user_plants', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('LOW_MOISTURE', 'HIGH_MOISTURE', 'SENSOR_OFFLINE', 'LOW_BATTERY', 'ANOMALY', 'WATERING_FAILED', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('sensors',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('hardware_version', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('auth_token', sa.String(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('moisture_dry_value', sa.Integer(), nullable=True),
    sa.Column('moisture_wet_value', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_index(op.f('ix_sensors_device_id'), 'sensors', ['device_id'], unique=True)
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_user_plant_id'), 'sensors', ['user_plant_id'], unique=False)
    op.create_table('watering_events',
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'AUTOMATIC', 'SCHEDULED', name='wateringtrigger'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='wateringstatus'), nullable=False),
    sa.Column('moisture_before', sa.Float(), nullable=True),
    sa.Column('moisture_after', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_events_id'), 'watering_events', ['id'], unique=False)
    op.create_index(op.f('ix_watering_events_user_plant_id'), 'watering_events', ['user_plant_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('moisture_pct', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('light_lux', sa.Integer(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_readings_time', 'sensor_readings', ['sensor_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_watering_events_user_plant_id'), table_name='watering_events')
    op.drop_index(op.f('ix_watering_events_id'), table_name='watering_events')
    op.drop_table('watering_events')
    op.drop_index(op.f('ix_sensors_user_plant_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_device_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_user_plants_user_id'), table_name='user_plants')
    op.drop_index(op.f('ix_user_plants_id'), table_name='user_plants')
    op.drop_table('user_plants')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plants_catalog_species_id'), table_name='plants_catalog')
    op.drop_index(op.f('ix_plants_catalog_scientific_name'), table_name='plants_catalog')
    op.drop_index(op.f('ix_plants_catalog_id'), table_name='plants_catalog')
    op.drop_index('idx_plant_scientific_name_search', table_name='plants_catalog')
    op.drop_table('plants_catalog')
    # ### end Alembic commands ###
